### ISSUE TITLE
Using Django

### ISSUE THREAD

**Issue by saikumarsura** [burhan/e24PaymentPipe#12]
def callKnet(request):
    file_path = os.path.join(os.path.split(__file__)[0], 'resource.cgn')
    pgw = Gateway(file_path, ALIAS)
    pgw.error_url = devlink + 'paymentgateway/errorknet'
    pgw.response_url = devlink + 'paymentgateway/gwKnet/'
    pgw.amount = 1.0
    amount = 1.0
    tid = Transaction.objects.create(total_amount=amount)
    gw_info = pgw.get_payment_url()
    pgw.trackid = str(tid.id) 
    payment_token = gw_info['paymentID']
    payment_url = gw_info['paymentURL']
    Transaction.objects.filter(id=tid.id).update(payment_id=payment_token)
    template_url = str(payment_url)+'?PaymentID='+str(payment_token)
    return HttpResponseRedirect(template_url)

def gwKnet(request):
    pg = request.body
    payment_id = request.POST.get('paymentid')
    trackid = request.POST.get('trackid')
    result = request.POST.get('result')
    postdate = request.POST.get('postdate')
    tranid = request.POST.get('tranid')
    ref = request.POST.get('ref')
    auth = request.POST.get('auth')
    a= {'payment_id':payment_id,'trackid':trackid,'result':result,'postdate':postdate,'tranid':tranid,'ref':ref,'auth':auth}
    return redirect('http://adminhtl.rehlat.ae/paymentgateway/success?payment_id='+str(payment_id))

def success(request):
    print 'i am success'
    template = get_template('pg_d.html')
    context = Context({'message':'Final'})
    html = template.render(context)
    print 'html',html
    return HttpResponse(dumps({'html':str(html),'status':'success'}))

Hi,
In the above code 
Step1: I am calling "**callKnet**" and able to see the KNet page and able to give my input.
Step2: KNet is posting me back to the "**gwKnet**" I am able to Capture the success response, At last, I am redirecting it to my success URL but KNet I unable to redirect me there.
Please do the needful.

**Comment by burhan** [comment]
On the second method `gwKnet` you need to output a string to the response, like this:

```python
url = 'http://adminhtl.rehlat.ae/paymentgateway/success?payment_id={}'.format(payment_id)
return HttpResponse('REDIRECT={}'.format(url))
```

**Comment by saikumarsura** [comment]
Thank you so much it worked.
