### ISSUE TITLE
zipfile.BadZipfile

### ISSUE THREAD

**Issue by baheywadea** [burhan/e24PaymentPipe#13]
When I trying to get link this Exception Error I get 
http://localhost:5000/12/34.345/ABC-TRACK/abc,foo@bar.com,hello
zipfile.BadZipfile
and i already paste the resource.cgn in project directory
this file downloaded from https://kpaytest.com.kw/kpg/resourceFileDownload.htm?actionparam=resourceList

**Comment by ali-tap** [comment]
+1

**Comment by burhan** [comment]
Use the new gateway integration kit at https://github.com/burhan/pyipay
