### ISSUE TITLE
Missing Sample Cart Implementation

### ISSUE THREAD

**Issue by prakhar1989** [burhan/e24PaymentPipe#8]
Thanks a lot for making this library! :+1: 

Quick question - The documentation mentions that there's a sample cart implementation lying at https://github.com/burhan/e24-sample-cart, however, there doesn't exist a sample implementation yet. Am I missing anything or is this pending?

Thanks!

**Comment by burhan** [comment]
There are two implementations available:

https://github.com/GDGKuwait/gae-knet-python (using GAE)
https://github.com/burhan/knet-client (Python + Flask)
