### ISSUE TITLE
[Errno 8] _ssl.c:507: EOF occurred in violation of protocol

### ISSUE THREAD

**Issue by huzzy143** [burhan/e24PaymentPipe#9]
Dear Burhan,

Thanks for your efforts in developing such a wonderful utility in KNET payment processing.

I am a beginner programmer in python and I have implemented this module in my project and it worked properly for few weeks. Suddenly now it is giving this error.

Can you please help me in solving this issue.

Regards,
Huzefa

**Comment by burhan** [comment]
This sounds like an issue with your network and not related to the KNET integration.
